import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    sectionTitle: {
        top: 25,
        left: 30,
        fontSize: 40,
        fontWeight: "600",
        color: '#FFF',
        zIndex: 10, 
        fontFamily: 'Nexa',
    },
    iphone1415ProMax1Inner: {
        top: 0,
        left: 0,
        backgroundColor: "#3d550c",
        borderStyle: "solid",
        borderColor: "#ecf87f",
        borderBottomWidth: 4,
        width: 440,
        height: 150,
        zIndex: 1,
        position: "absolute",
    },
    tasksWrapper: {
        backgroundColor: '#81B622',
        flex: 1,
    },
    sectionheader: {
        top: 140,
        textAlign: 'center',
        fontSize: 40,
        fontWeight: "500",
        color: '#FFF',
        zIndex: 10, 
        fontFamily: 'Nexa',
    },
    sectionbody1: {
        top: 200,
        left: 20,
        fontSize: 30,
        fontWeight: "500",
        color: '#FFF',
        zIndex: 10, 
        fontFamily: 'Nexa',
    },    
    inputbox1: {
        top: 225,
        left: 20,
        width: 380, 
    },
    sectionbody2: {
        top: 265,
        left: 20,
        fontSize: 30,
        fontWeight: "500",
        color: '#FFF',
        zIndex: 10, 
        fontFamily: 'Nexa',
    },    
    inputbox2: {
        top: 240,
        left: 20,
        strokeWidth: 2.5,
        width: 380,
    },
    inputbox3: {
        top: 325,
        left: 20,
        strokeWidth: 2.5,
        width: 380,
    },
    sectionbody3: {
        position: 'absolute',
        top: 615,
        fontSize: 30,
        left: 20,
        fontWeight: "500",
        color: '#FFF',
        zIndex: 10, 
        fontFamily: 'Nexa',
    },
    opencheckcircle: {
        strokeWidth: 2,
        strokeLinecap: 'round',
        alignContent: 'right',
        top: 845,
        right: 40,
        position: 'absolute',
    },
    filledcheckcircle: {
        strokeWidth: 2,
        strokeLinecap: 'round',
        alignSelf: 'flex-end',
        right: 40,
        top: 485,
        position: 'absolute',
    },
    closexwhite: {
        position: 'absolute',
        top: 180,
        left: 360,
        strokeWidth: 3,
        strokeLinecap: 'round',
    },
    dateBox1: {
        height: 40,
        backgroundColor: 'white',
        borderRadius: 20,
        borderColor: '#3D550C',
        borderWidth: 3,
        justifyContent: 'center',
        paddingHorizontal: 10,
        marginHorizontal: 20,
        top: 280,
    },
    dateBox2: {
        height: 40,
        backgroundColor: 'white',
        borderRadius: 20,
        borderColor: '#3D550C',
        borderWidth: 3,
        justifyContent: 'center',
        paddingHorizontal: 10,
        marginHorizontal: 20,
        top: 355,
        width: 380, 
    },
    dateText1: {
        fontSize: 16,
        color: '#3D550C',
    },
    dateText2: {
        fontSize: 16,
        color: '#3D550C',
    },
    pickerContainer: {
        backgroundColor: 'white',
        borderRadius: 20,
        padding: 10,
        marginTop: 10,
        marginHorizontal: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 5,
        left: 15,
        top: 95,
        zIndex: 20,
        position: 'absolute'
    },
    pickerContainer2: {
        backgroundColor: 'white',
        borderRadius: 20,
        padding: 10,
        marginTop: 10,
        marginHorizontal: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 5,
        left: 15,
        top: 95,
        zIndex: 20,
        position: 'absolute'
    },    
});