import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    sectionTitle: {
      top: 25,
      left: 30,
      fontSize: 40,
      fontWeight: "600",
      color: '#FFF',
      zIndex: 10, 
      fontFamily: 'Nexa',
    },
    tasksWrapper: {
      backgroundColor: '#81B622',
      flex: 1,
    },
    addbutton: {
      position: 'absolute',
      bottom: 30,
      right: 30,
      width: 60,
      height: 60,
      zIndex: 999, 
    },
    firstSection1: {
      top: 125,
      textAlign: 'center',
      fontSize: 35,
      fontWeight: "500",
      color: '#FFF',
      zIndex: 10, 
      fontFamily: 'Nexa',
      marginBottom: 150,
    },
    firstSection2: {
      fontSize: 20,
      fontWeight: "500",
      color: '#FFF',
      zIndex: 10, 
      fontFamily: 'Nexa',
      lineHeight: 23, 
      flexWrap: 'wrap',
    },
    firstSection3: {
      flexWrap: 'wrap',
      fontSize: 17,
      fontWeight: "200",
      color: '#FFF',
      zIndex: 10, 
      fontFamily: 'Nexa',
    },
    checkicon: {
      position: 'absolute',
      strokeWidth: 2,
      strokeLinecap: 'round',
    },
    closex: {
      strokeWidth: 2.5,
      strokeLinecap: 'round',
    },
    iphone1415ProMax1Inner: {
      top: 0,
      left: 0,
      backgroundColor: "#3d550c",
      borderStyle: "solid",
      borderColor: "#ecf87f",
      borderBottomWidth: 4,
      width: 430,
      height: 150,
      zIndex: 1,
      position: "absolute",
    },
    smallbox: {
    },
    smallbox2: {
      position:'absolute',
    },
    tasktangle1: {
      strokeWidth: 3,
    },
    tasktangle2: {
      strokeWidth: 3,
    },
    deletebox: {
      top: 40,
      alignSelf: 'center',
    },
    deletetext1: {
      fontSize: 30,
      fontFamily: 'Nexa',
      fontWeight: "600",
      alignSelf: 'center',
      zIndex: 21, 
      top: -240,
      color: 'white',
    },
    deletetext2: {
      alignSelf: 'center',
      fontSize: 23,
      fontFamily: 'Nexa',
      fontWeight: "600",
      bottom: 470,
      zIndex: 21, 
      position: 'absolute',
      color: 'white',
    },
    deletetext3: {
      alignSelf: 'center',
      fontSize: 23,
      fontFamily: 'Nexa',
      fontWeight: "600",
      zIndex: 21, 
      top: -140,
      color: 'white',
    },
    deletetext4: {
      fontSize: 23,
      fontFamily: 'Nexa',
      fontWeight: "600",
      top: -60,
      right: 100,
      zIndex: 21, 
      color: 'white',
    },
    deletetext5: {
      fontSize: 23,
      fontFamily: 'Nexa',
      fontWeight: "600",
      top: -83,
      left: 100,
      color: 'white',
    },
      
});